server:
  port: 2003
spring:
  application:
    name: xiao-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.221:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #文章微服务
        - id: xiao-article
          uri: lb://xiao-article
          predicates:
            - Path=/article/**
          filters:
            - StripPrefix= 1
        #用户微服务
        - id: axz-user
          uri: lb://xiao-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1
