server:
  port: 2006
spring:
  application:
    name: xiao-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.221:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/xiao_search?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: plus.axz.model.search.pojos

#取消对elastsearch的健康检查
management:
  health:
    elasticsearch:
      enabled: false
#自定义elasticsearch连接配置
elasticsearch:
  host: 192.168.20.221
  port: 9200
