server:
  port: 2005
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  application:
    name: xiao-comment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.221:8848
