server:
   port: 1124
spring:
 application:
   name: xiao-article
 cloud:
   nacos:
     discovery:
       server-addr: 192.168.20.221:8848
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3307/xiao_article?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
   username: root
   password: 123456
 servlet:
   multipart:
   max-file-size: 100MB
 # 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
 mybatis-plus:
   configuration:
     map-underscore-to-camel-case: false # 数据库下划线自动转驼峰标示关闭(为true，就简单粗暴的把下划线干掉了)
   mapper-locations: classpath*:mapper/*.xml
     # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
   type-aliases-package: plus.axz.model.article.pojos
